// constants.ts (or wherever COLLECTIONS_EXTENDED is defined)

export const COLLECTIONS_EXTENDED = [
  {
    id: 'series-01-art-deco',
    category: 'Art Deco',
    title: 'The Twenties Collection',
    subtitle: 'Industrial precision meets Art Deco elegance.',
    description: 'A decade of craftsmanship in borosilicate glass.',
    mainLink: 'https://janewest.com/collections/the-twenties-collection',
    seoCluster: 'Art Deco glassware, luxury smoking accessories, borosilicate engineering',
    featuredItems: ['Water Pipes', 'Bubblers', 'Beakers', 'Ashtrays'],
    itemLinks: {
      'Water Pipes': 'https://janewest.com/products/twenties-water-pipe-cobalt',
      'Bubblers': 'https://janewest.com/collections/the-twenties-collection-bubbler',
      'Beakers': 'https://janewest.com/products/twenties-collection-hand-pipe-clear',
      'Ashtrays': 'https://janewest.com/products/twenties-collection-ashtray-clear',
    },
  },
  {
    id: 'series-02-travel',
    category: 'Travel',
    title: 'The Travel Collection',
    subtitle: 'Luxury travel tools for modern rituals.',
    description: 'Elegant flasks, compact kits, and portable accessories.',
    mainLink: 'https://janewest.com/collections/travel-collection',
    seoCluster: 'Travel flasks, luxury compact kits, Art Deco design',
    featuredItems: ['The Classic', 'The Wand', 'The Compact'],
    itemLinks: {
      'The Classic': 'https://janewest.com/products/janewest-classic',
      'The Wand': 'https://www.iheartjane.com/products/396896/grav-jane-west-wand',
      'The Compact': 'https://janewest.com/products/janewest-compact',
    },
  },
  {
    id: 'series-03-daily',
    category: 'Daily',
    title: 'Daily Accessories',
    subtitle: 'Everyday luxury in functional form.',
    description: 'Solo one-hitters, cubes, and outdoor pipes for daily use.',
    mainLink: 'https://janewest.com/collections/daily-accessories',
    seoCluster: 'Daily smoking accessories, portable glassware, functional art',
    featuredItems: ['Solo One-Hitter', 'The Cube', 'Outdoor Pipe'],
    itemLinks: {
      'Solo One-Hitter': 'https://janewest.com/products/the-solo',
      'The Cube': 'https://janewest.com/products/the-cube',
      'Outdoor Pipe': 'https://janewest.com/products/the-outdoor-pipe',
    },
  },
  {
    id: 'series-04-collaboration',
    category: 'Collaboration',
    title: 'Jane West x GRAV',
    subtitle: 'Collaborative precision and artistic mastery.',
    description: 'Beakers, steamrollers, and bubblers designed with GRAV Labs.',
    mainLink: 'https://janewest.com/collections/jane-west-x-grav',
    seoCluster: 'Collaborative glassware, GRAV Labs, premium beakers',
    featuredItems: ['Beakers', 'Steamrollers', 'Bubblers'],
    itemLinks: {
      'Beakers': 'https://smokea.com/products/jane-west-x-grav-labs-beaker-bong',
      'Steamrollers': 'https://www.leafly.com/brands/caliconnected/products/caliconnected-grav-labs-jane-west-steamroller',
      'Bubblers': 'https://www.wickiepipes.com/et/collections/jane-west',
    },
  },
  {
    id: 'series-05-wellness',
    category: 'Wellness',
    title: 'Jane’s Brew',
    subtitle: 'Calm, happy, and serene rituals in a cup.',
    description: 'CBD K-Cups and capsules to enhance your daily wellness.',
    mainLink: 'https://cbdfarmhouse.com/shop/cbd-hemp-products/cbd-hemp-edibles/janes-brew-cup-of-coffee/',
    seoCluster: 'CBD wellness, Jane’s Brew coffee, health supplements',
    featuredItems: ['Chill/Happy/Serenity K-Cups', 'CBD Capsules'],
    itemLinks: {
      'Chill/Happy/Serenity K-Cups': 'https://cbdfarmhouse.com/shop/cbd-hemp-products/cbd-hemp-edibles/janes-brew-cup-of-coffee/',
      'CBD Capsules': 'https://cbdfarmhouse.com/shop/cbd-hemp-products/cbd-hemp-edibles/janes-brew-cup-of-coffee/',
    },
  },
];
